/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ashish
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newEntry_button = new javax.swing.JButton();
        newBook_button = new javax.swing.JButton();
        history_button = new javax.swing.JButton();
        issue_button = new javax.swing.JButton();
        return_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newEntry_button.setText("New Student Entry");
        newEntry_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntry_buttonActionPerformed(evt);
            }
        });

        newBook_button.setText("New Book");
        newBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBook_buttonActionPerformed(evt);
            }
        });

        history_button.setText("History");
        history_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_buttonActionPerformed(evt);
            }
        });

        issue_button.setText("Issue Book");
        issue_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_buttonActionPerformed(evt);
            }
        });

        return_button.setText("Return Book");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(newEntry_button)
                .addGap(69, 69, 69)
                .addComponent(newBook_button)
                .addGap(73, 73, 73)
                .addComponent(history_button)
                .addGap(66, 66, 66)
                .addComponent(issue_button)
                .addGap(63, 63, 63)
                .addComponent(return_button)
                .addGap(62, 62, 62)
                .addComponent(logout_button)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEntry_button)
                    .addComponent(newBook_button)
                    .addComponent(history_button)
                    .addComponent(issue_button)
                    .addComponent(return_button)
                    .addComponent(logout_button))
                .addContainerGap(725, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
        
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void newEntry_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntry_buttonActionPerformed
        // TODO add your handling code here:
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_newEntry_buttonActionPerformed

    private void newBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBook_buttonActionPerformed
        // TODO add your handling code here:
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBook_buttonActionPerformed

    private void issue_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_buttonActionPerformed
        // TODO add your handling code here:
        new IssueBook().setVisible(true);
    }//GEN-LAST:event_issue_buttonActionPerformed

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        // TODO add your handling code here:
        new ReturnBook().setVisible(true);
    }//GEN-LAST:event_return_buttonActionPerformed

    private void history_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_buttonActionPerformed
        // TODO add your handling code here:
        new History().setVisible(true);
    }//GEN-LAST:event_history_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton history_button;
    private javax.swing.JButton issue_button;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton newBook_button;
    private javax.swing.JButton newEntry_button;
    private javax.swing.JButton return_button;
    // End of variables declaration//GEN-END:variables
}
